name: Test

on:
  workflow_dispatch: ~
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run prek
        run: uv run prek run --all-files --show-diff-on-failure

      - name: Pylint
        run: uv run pylint src/spinev_ble

      - name: Test
        run: uv run pytest --cov=spinev_ble --cov-report=xml
